import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { dirname } from 'path';
import { PATHS } from './config.js';

// 전경색 기본값
export const FG_DEFAULTS = {
  C_BRANCH: { name: 'Branch', code: 93 },
  C_TREE: { name: 'Worktree', code: 92 },
  C_DIR: { name: 'Directory', code: 96 },
  C_MODEL: { name: 'Model', code: 95 },
  C_STATUS: { name: 'Status', code: 111 },
  C_SYNC: { name: 'Sync', code: 141 },
  C_RATE: { name: 'Rate', code: 229 },
  C_BURN: { name: 'Burn', code: 216 },
  C_TIME: { name: 'Time', code: 75 },
  C_CTX: { name: 'Context', code: 92 },
};

// badges용 배경색 기본값 (개별 요소)
export const BG_BADGES_DEFAULTS = {
  C_BG_BRANCH: { name: 'BG Branch', code: 58 },
  C_BG_TREE: { name: 'BG Worktree', code: 22 },
  C_BG_DIR: { name: 'BG Dir', code: 23 },
  C_BG_STATUS: { name: 'BG Status', code: 24 },
  C_BG_SYNC: { name: 'BG Sync', code: 53 },
  C_BG_MODEL: { name: 'BG Model', code: 53 },
  C_BG_RATE: { name: 'BG Rate', code: 58 },
  C_BG_TIME: { name: 'BG Time', code: 24 },
  C_BG_BURN: { name: 'BG Burn', code: 94 },
};

// bars용 배경색 기본값 (그룹)
export const BG_BARS_DEFAULTS = {
  C_BG_LOC: { name: 'BG Location', code: 23 },
  C_BG_GIT: { name: 'BG Git', code: 24 },
  C_BG_SES: { name: 'BG Session', code: 53 },
};

// 아이콘 정의
export const ICONS = {
  emoji: {
    BRANCH: '🔱',
    TREE: '🌿',
    DIR: '📂',
    STATUS: '💾',
    SYNC: '🔮',
    MODEL: '🧠',
    TIME: '⏳',
    SESSION: '💬',
    COST: '💰',
    THEME: '🎨',
    CTX: '🔋',
  },
  nerd: {
    BRANCH: '󰘬 ',
    TREE: '󰙅 ',
    DIR: '󰝰 ',
    STATUS: '󰊤 ',
    SYNC: '󰓦 ',
    MODEL: '󰚩 ',
    TIME: '󰅐 ',
    SESSION: '󰭻 ',
    COST: '󰆼 ',
    THEME: '󰉼 ',
    CTX: '󰁹 ',
  }
};

// 레이아웃 목록
export const LAYOUTS = ['1line', '2line', 'card', 'bars', 'badges'];

// 배경색이 필요한 레이아웃
export const LAYOUTS_WITH_BG = ['bars', 'badges'];

// 후방 호환성: BG_DEFAULTS는 BG_BADGES_DEFAULTS의 별칭
export const BG_DEFAULTS = BG_BADGES_DEFAULTS;

/**
 * 커스텀 색상 로드
 * 참고: layout/iconType은 프리뷰 전용이므로 항상 기본값(2line/nerd) 반환
 */
export function loadCustomColors() {
  const fg = {};
  const bgBadges = {};
  const bgBars = {};
  // 프리뷰용 기본값 (저장되지 않음)
  const layout = '2line';
  const iconType = 'nerd';

  // 기본값으로 초기화
  for (const [key, val] of Object.entries(FG_DEFAULTS)) {
    fg[key] = val.code;
  }
  for (const [key, val] of Object.entries(BG_BADGES_DEFAULTS)) {
    bgBadges[key] = val.code;
  }
  for (const [key, val] of Object.entries(BG_BARS_DEFAULTS)) {
    bgBars[key] = val.code;
  }

  // 커스텀 파일이 있으면 색상만 로드
  if (existsSync(PATHS.customColor)) {
    try {
      const content = readFileSync(PATHS.customColor, 'utf-8');

      // 전경색 파싱
      for (const key of Object.keys(FG_DEFAULTS)) {
        const match = content.match(new RegExp(`${key}_CODE=(\\d+)`));
        if (match) {
          fg[key] = parseInt(match[1], 10);
        }
      }

      // badges용 배경색 파싱
      for (const key of Object.keys(BG_BADGES_DEFAULTS)) {
        const match = content.match(new RegExp(`${key}_CODE=(\\d+)`));
        if (match) {
          bgBadges[key] = parseInt(match[1], 10);
        }
      }

      // bars용 배경색 파싱
      for (const key of Object.keys(BG_BARS_DEFAULTS)) {
        const match = content.match(new RegExp(`${key}_CODE=(\\d+)`));
        if (match) {
          bgBars[key] = parseInt(match[1], 10);
        }
      }
    } catch {
      // 파싱 실패 시 기본값 사용
    }
  }

  // 후방 호환성: bg는 bgBadges의 별칭
  return { fg, bg: bgBadges, bgBadges, bgBars, layout, iconType };
}

/**
 * 커스텀 색상 저장
 * 참고: layout/iconType은 프리뷰 전용이므로 저장하지 않음
 */
export function saveCustomColors(fg, bgBadges, bgBars) {
  // 디렉토리 생성
  const dir = dirname(PATHS.customColor);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  let content = `#!/bin/bash
# zstheme Custom Colors
# Generated by zstheme Color Editor
# Usage: Set CLAUDE_THEME="custom-<layout>[-nerd]" to use these colors
# Examples: custom-2line, custom-badges-nerd, custom-bars

`;

  // 전경색
  content += '# Foreground Colors\n';
  for (const [key, defaultVal] of Object.entries(FG_DEFAULTS)) {
    const code = fg[key] ?? defaultVal.code;
    content += `${key}=$'\\033[38;5;${code}m'\n`;
    content += `${key}_CODE=${code}\n`;
  }

  // badges용 배경색
  content += '\n# Background Colors (badges layout)\n';
  for (const [key, defaultVal] of Object.entries(BG_BADGES_DEFAULTS)) {
    const code = bgBadges[key] ?? defaultVal.code;
    content += `${key}=$'\\033[48;5;${code}m'\n`;
    content += `${key}_CODE=${code}\n`;
  }

  // bars용 배경색
  content += '\n# Background Colors (bars layout)\n';
  for (const [key, defaultVal] of Object.entries(BG_BARS_DEFAULTS)) {
    const code = bgBars[key] ?? defaultVal.code;
    content += `${key}=$'\\033[48;5;${code}m'\n`;
    content += `${key}_CODE=${code}\n`;
  }

  writeFileSync(PATHS.customColor, content, { mode: 0o644 });

  return PATHS.customColor;
}

/**
 * 색상 기본값으로 리셋
 */
export function resetToDefaults() {
  const fg = {};
  const bgBadges = {};
  const bgBars = {};

  for (const [key, val] of Object.entries(FG_DEFAULTS)) {
    fg[key] = val.code;
  }
  for (const [key, val] of Object.entries(BG_BADGES_DEFAULTS)) {
    bgBadges[key] = val.code;
  }
  for (const [key, val] of Object.entries(BG_BARS_DEFAULTS)) {
    bgBars[key] = val.code;
  }

  // 후방 호환성: bg는 bgBadges의 별칭
  return { fg, bg: bgBadges, bgBadges, bgBars, layout: '2line', iconType: 'nerd' };
}
