import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { dirname } from 'path';
import { PATHS } from './config.js';

// 전경색 기본값
export const FG_DEFAULTS = {
  C_BRANCH: { name: 'Branch', code: 93 },
  C_TREE: { name: 'Worktree', code: 92 },
  C_DIR: { name: 'Directory', code: 96 },
  C_MODEL: { name: 'Model', code: 95 },
  C_STATUS: { name: 'Status', code: 111 },
  C_SYNC: { name: 'Sync', code: 141 },
  C_RATE: { name: 'Rate', code: 229 },
  C_BURN: { name: 'Burn', code: 216 },
  C_TIME: { name: 'Time', code: 75 },
  C_CTX: { name: 'Context', code: 92 },
};

// 배경색 기본값
export const BG_DEFAULTS = {
  C_BG_BRANCH: { name: 'BG Branch', code: 58 },
  C_BG_TREE: { name: 'BG Worktree', code: 22 },
  C_BG_DIR: { name: 'BG Dir', code: 23 },
  C_BG_STATUS: { name: 'BG Status', code: 24 },
  C_BG_SYNC: { name: 'BG Sync', code: 53 },
  C_BG_MODEL: { name: 'BG Model', code: 53 },
  C_BG_LOC: { name: 'BG LOC', code: 23 },
  C_BG_GIT: { name: 'BG GIT', code: 24 },
  C_BG_SES: { name: 'BG SES', code: 53 },
};

/**
 * 커스텀 색상 로드
 */
export function loadCustomColors() {
  const fg = {};
  const bg = {};

  // 기본값으로 초기화
  for (const [key, val] of Object.entries(FG_DEFAULTS)) {
    fg[key] = val.code;
  }
  for (const [key, val] of Object.entries(BG_DEFAULTS)) {
    bg[key] = val.code;
  }

  // 커스텀 파일이 있으면 로드
  if (existsSync(PATHS.customColor)) {
    try {
      const content = readFileSync(PATHS.customColor, 'utf-8');

      // 전경색 파싱
      for (const key of Object.keys(FG_DEFAULTS)) {
        const match = content.match(new RegExp(`${key}_CODE=(\\d+)`));
        if (match) {
          fg[key] = parseInt(match[1], 10);
        }
      }

      // 배경색 파싱
      for (const key of Object.keys(BG_DEFAULTS)) {
        const match = content.match(new RegExp(`${key}_CODE=(\\d+)`));
        if (match) {
          bg[key] = parseInt(match[1], 10);
        }
      }
    } catch {
      // 파싱 실패 시 기본값 사용
    }
  }

  return { fg, bg };
}

/**
 * 커스텀 색상 저장
 */
export function saveCustomColors(fg, bg) {
  // 디렉토리 생성
  const dir = dirname(PATHS.customColor);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  let content = `#!/bin/bash
# zstheme Custom Colors
# Generated by zstheme Color Editor
# Usage: Set CLAUDE_THEME="custom-<layout>" to use these colors

`;

  // 전경색
  content += '# Foreground Colors\n';
  for (const [key, defaultVal] of Object.entries(FG_DEFAULTS)) {
    const code = fg[key] ?? defaultVal.code;
    content += `${key}=$'\\033[38;5;${code}m'\n`;
    content += `${key}_CODE=${code}\n`;
  }

  content += '\n# Background Colors\n';
  for (const [key, defaultVal] of Object.entries(BG_DEFAULTS)) {
    const code = bg[key] ?? defaultVal.code;
    content += `${key}=$'\\033[48;5;${code}m'\n`;
    content += `${key}_CODE=${code}\n`;
  }

  writeFileSync(PATHS.customColor, content, { mode: 0o644 });

  return PATHS.customColor;
}

/**
 * 색상 기본값으로 리셋
 */
export function resetToDefaults() {
  const fg = {};
  const bg = {};

  for (const [key, val] of Object.entries(FG_DEFAULTS)) {
    fg[key] = val.code;
  }
  for (const [key, val] of Object.entries(BG_DEFAULTS)) {
    bg[key] = val.code;
  }

  return { fg, bg };
}
