import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { dirname } from 'path';
import { PATHS } from './config.js';
import { parseThemeContract } from './themeContract.js';
import { RAINBOW_COLORS, LSD_COLORS, MONO_CYCLE } from '../renderer/palette.js';

// 전경색 기본값
// 2line 시각 순서: Line1(BRANCH,TREE,DIR,STATUS,SYNC) Line2(MODEL,RATE,TIME,BURN)
// CTX는 contextPct에 의한 고정값이므로 편집 대상 아님
export const FG_DEFAULTS = {
  C_BRANCH: { name: 'Branch', code: 11 },
  C_TREE: { name: 'Worktree', code: 10 },
  C_DIR: { name: 'Directory', code: 14 },
  C_STATUS: { name: 'Status', code: 111 },
  C_SYNC: { name: 'Sync', code: 141 },
  C_MODEL: { name: 'Model', code: 13 },
  C_RATE: { name: 'Rate', code: 229 },
  C_TIME: { name: 'Time', code: 75 },
  C_BURN: { name: 'Burn', code: 216 },
};

// badges용 배경색 기본값 (개별 요소)
export const BG_BADGES_DEFAULTS = {
  C_BG_BRANCH: { name: 'BG Branch', code: 58 },
  C_BG_TREE: { name: 'BG Worktree', code: 22 },
  C_BG_DIR: { name: 'BG Dir', code: 23 },
  C_BG_STATUS: { name: 'BG Status', code: 24 },
  C_BG_SYNC: { name: 'BG Sync', code: 53 },
  C_BG_MODEL: { name: 'BG Model', code: 53 },
  C_BG_RATE: { name: 'BG Rate', code: 58 },
  C_BG_TIME: { name: 'BG Time', code: 24 },
  C_BG_BURN: { name: 'BG Burn', code: 94 },
};

// bars용 배경색 기본값 (그룹)
export const BG_BARS_DEFAULTS = {
  C_BG_LOC: { name: 'BG Location', code: 23 },
  C_BG_GIT: { name: 'BG Git', code: 24 },
  C_BG_SES: { name: 'BG Session', code: 53 },
};

// 아이콘 정의
export const ICONS = {
  emoji: {
    BRANCH: '🔱',
    TREE: '🌿',
    DIR: '📂',
    STATUS: '💾',
    SYNC: '🔮',
    MODEL: '🧠',
    TIME: '⏳',
    SESSION: '💬',
    COST: '💰',
    THEME: '🎨',
    CTX: '🔋',
  },
  nerd: {
    BRANCH: '󰘬 ',
    TREE: '󰙅 ',
    DIR: '󰝰 ',
    STATUS: '󰊤 ',
    SYNC: '󰓦 ',
    MODEL: '󰚩 ',
    TIME: '󰅐 ',
    SESSION: '󰭻 ',
    COST: '󰆼 ',
    THEME: '󰉼 ',
    CTX: '󰁹 ',
  }
};

// 배경색이 필요한 레이아웃
export const LAYOUTS_WITH_BG = ['bars', 'badges'];

// 후방 호환성: BG_DEFAULTS는 BG_BADGES_DEFAULTS의 별칭
export const BG_DEFAULTS = BG_BADGES_DEFAULTS;

/**
 * 커스텀 색상 로드
 * 참고: layout/iconType은 프리뷰 전용이므로 항상 기본값(2line/nerd) 반환
 */
export function loadCustomColors() {
  const fg = {};
  const bgBadges = {};
  const bgBars = {};
  // 현재 활성 테마에서 layout/icon 감지 (미설정 시 2line-nerd 기본)
  let currentTheme = '2line';
  if (existsSync(PATHS.themeConfig)) {
    try {
      const content = readFileSync(PATHS.themeConfig, 'utf-8');
      const match = content.match(/CLAUDE_THEME="([^"]+)"/);
      if (match) currentTheme = match[1];
    } catch { /* use default */ }
  }
  const parsed = parseThemeContract(currentTheme);
  const layout = parsed.layout || '2line';
  const iconType = parsed.icon || 'nerd';

  // 기본값으로 초기화
  for (const [key, val] of Object.entries(FG_DEFAULTS)) {
    fg[key] = val.code;
  }
  for (const [key, val] of Object.entries(BG_BADGES_DEFAULTS)) {
    bgBadges[key] = val.code;
  }
  for (const [key, val] of Object.entries(BG_BARS_DEFAULTS)) {
    bgBars[key] = val.code;
  }

  // 커스텀 파일이 있으면 색상만 로드
  if (existsSync(PATHS.customColor)) {
    try {
      const content = readFileSync(PATHS.customColor, 'utf-8');

      // 전경색 파싱
      for (const key of Object.keys(FG_DEFAULTS)) {
        const match = content.match(new RegExp(`${key}_CODE=(\\d+)`));
        if (match) {
          fg[key] = parseInt(match[1], 10);
        }
      }

      // badges용 배경색 파싱
      for (const key of Object.keys(BG_BADGES_DEFAULTS)) {
        const match = content.match(new RegExp(`${key}_CODE=(\\d+)`));
        if (match) {
          bgBadges[key] = parseInt(match[1], 10);
        }
      }

      // bars용 배경색 파싱
      for (const key of Object.keys(BG_BARS_DEFAULTS)) {
        const match = content.match(new RegExp(`${key}_CODE=(\\d+)`));
        if (match) {
          bgBars[key] = parseInt(match[1], 10);
        }
      }
    } catch (e) {
      // 커스텀 색상 파일 파싱 실패 시 기본값 유지
    }
  }

  // 후방 호환성: bg는 bgBadges의 별칭
  return { fg, bg: bgBadges, bgBadges, bgBars, layout, iconType };
}

/**
 * 커스텀 색상 저장
 * 참고: layout/iconType은 프리뷰 전용이므로 저장하지 않음
 */
export function saveCustomColors(fg, bgBadges, bgBars) {
  // 디렉토리 생성
  const dir = dirname(PATHS.customColor);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  let content = `#!/bin/bash
# zstheme Custom Colors
# Generated by zstheme Color Editor
# Usage: Set CLAUDE_THEME="custom-<layout>[-nerd]" to use these colors
# Examples: custom-2line, custom-badges-nerd, custom-bars

`;

  // 전경색
  content += '# Foreground Colors\n';
  for (const [key, defaultVal] of Object.entries(FG_DEFAULTS)) {
    const code = fg[key] ?? defaultVal.code;
    content += `${key}=$'\\033[38;5;${code}m'\n`;
    content += `${key}_CODE=${code}\n`;
  }

  // badges용 배경색
  content += '\n# Background Colors (badges layout)\n';
  for (const [key, defaultVal] of Object.entries(BG_BADGES_DEFAULTS)) {
    const code = bgBadges[key] ?? defaultVal.code;
    content += `${key}=$'\\033[48;5;${code}m'\n`;
    content += `${key}_CODE=${code}\n`;
  }

  // bars용 배경색
  content += '\n# Background Colors (bars layout)\n';
  for (const [key, defaultVal] of Object.entries(BG_BARS_DEFAULTS)) {
    const code = bgBars[key] ?? defaultVal.code;
    content += `${key}=$'\\033[48;5;${code}m'\n`;
    content += `${key}_CODE=${code}\n`;
  }

  writeFileSync(PATHS.customColor, content, { mode: 0o644 });

  return PATHS.customColor;
}

/**
 * ANSI 256 색상 코드 → hex 변환
 */
export function ansi256ToHex(code) {
  // 0-7: 표준색
  const STANDARD = [
    '#000000', '#800000', '#008000', '#808000',
    '#000080', '#800080', '#008080', '#c0c0c0',
  ];
  // 8-15: 밝은색
  const BRIGHT = [
    '#808080', '#ff0000', '#00ff00', '#ffff00',
    '#0000ff', '#ff00ff', '#00ffff', '#ffffff',
  ];

  if (code < 8) return STANDARD[code];
  if (code < 16) return BRIGHT[code - 8];

  // 16-231: 6x6x6 큐브
  if (code < 232) {
    const idx = code - 16;
    const r = Math.floor(idx / 36);
    const g = Math.floor((idx % 36) / 6);
    const b = idx % 6;
    const toVal = (v) => v === 0 ? 0 : 55 + v * 40;
    const hex = (v) => toVal(v).toString(16).padStart(2, '0');
    return `#${hex(r)}${hex(g)}${hex(b)}`;
  }

  // 232-255: 그레이스케일
  const grey = 8 + (code - 232) * 10;
  const h = grey.toString(16).padStart(2, '0');
  return `#${h}${h}${h}`;
}

// Pastel FG: 렌더러 실제 색상 기준 (basic ANSI bright + ANSI 256)
const PASTEL_HEX = [
  '#ffff00',  // BRANCH: \033[93m bright yellow
  '#00ff00',  // TREE: \033[92m bright green
  '#00ffff',  // DIR: \033[96m bright cyan
  '#ff00ff',  // MODEL: \033[95m bright magenta
  '#87afff',  // STATUS: fg(111)
  '#af87ff',  // SYNC: fg(141)
  '#ffffaf',  // RATE: fg(229)
  '#ffaf87',  // BURN: fg(216)
  '#5fafff',  // TIME: fg(75)
];

function rgbToHex(r, g, b) {
  return '#' + [r, g, b].map(v => v.toString(16).padStart(2, '0')).join('');
}

function samplePalette(palette, count = 10) {
  const step = palette.length / count;
  return Array.from({ length: count }, (_, i) => {
    const [r, g, b] = palette[Math.floor(i * step)];
    return rgbToHex(r, g, b);
  });
}

/**
 * 테마 색상 팔레트 조회 (hex 배열)
 * 렌더러의 실제 색상 로직과 일치하도록 구현
 */
export function getThemeColorPalette(themeName) {
  const { color, animation } = parseThemeContract(themeName);

  // 애니메이션 테마: RGB 팔레트에서 샘플링
  if (animation !== 'static') {
    let palette;
    if (color === 'mono') palette = MONO_CYCLE;
    else if (animation === 'lsd') palette = LSD_COLORS;
    else palette = RAINBOW_COLORS;
    return samplePalette(palette);
  }

  // static mono
  if (color === 'mono') {
    return [ansi256ToHex(250)];
  }

  // static custom (ANSI 256 codes)
  if (color === 'custom') {
    const { fg } = loadCustomColors();
    return Object.values(fg).map(ansi256ToHex);
  }

  // static pastel
  return PASTEL_HEX;
}

/**
 * 색상 기본값으로 리셋
 */
export function resetToDefaults() {
  const fg = {};
  const bgBadges = {};
  const bgBars = {};

  for (const [key, val] of Object.entries(FG_DEFAULTS)) {
    fg[key] = val.code;
  }
  for (const [key, val] of Object.entries(BG_BADGES_DEFAULTS)) {
    bgBadges[key] = val.code;
  }
  for (const [key, val] of Object.entries(BG_BARS_DEFAULTS)) {
    bgBars[key] = val.code;
  }

  // 후방 호환성: bg는 bgBadges의 별칭
  return { fg, bg: bgBadges, bgBadges, bgBars, layout: '2line', iconType: 'nerd' };
}
