#!/bin/bash
# zstheme Color Editor - 저장/로드 기능

# ============================================================
# 설정 디렉토리
# ============================================================

CONFIG_DIR="$HOME/.config/zstheme"
CUSTOM_COLOR_FILE="$CONFIG_DIR/custom-color.sh"

# ============================================================
# 커스텀 색상 저장
# ============================================================

save_custom_colors() {
    # 디렉토리 생성
    mkdir -p "$CONFIG_DIR"

    # 파일 생성
    cat > "$CUSTOM_COLOR_FILE" << 'HEADER'
#!/bin/bash
# zstheme Custom Color Module - 사용자 커스텀 색상
# Generated by zstheme --edit
# Do not edit manually unless you know what you're doing

# ============================================================
# 색상 코드 (256 color palette)
# ============================================================

HEADER

    # 전경색 코드 저장
    echo "# Foreground color codes" >> "$CUSTOM_COLOR_FILE"
    for i in "${!FG_VARS[@]}"; do
        echo "${FG_VARS[$i]}_CODE=${FG_VALUES[$i]}" >> "$CUSTOM_COLOR_FILE"
    done

    echo "" >> "$CUSTOM_COLOR_FILE"

    # 배경색 코드 저장
    echo "# Background color codes" >> "$CUSTOM_COLOR_FILE"
    for i in "${!BG_VARS[@]}"; do
        echo "${BG_VARS[$i]}_CODE=${BG_VALUES[$i]}" >> "$CUSTOM_COLOR_FILE"
    done

    # init_colors 함수 생성
    cat >> "$CUSTOM_COLOR_FILE" << 'INIT_FUNC'

# ============================================================
# 색상 초기화 함수 (기본 color.sh 구조 유지)
# ============================================================

init_colors() {
    RST=$'\033[0m'

    # Git 상태 색상 (저장된 값 사용)
    C_DIM_STATUS=$'\033[38;5;'"${C_STATUS_CODE}"'m'
    C_BRIGHT_STATUS=$'\033[1;38;5;'"${C_STATUS_CODE}"'m'
    C_DIM_SYNC=$'\033[38;5;'"${C_SYNC_CODE}"'m'
    C_BRIGHT_SYNC=$'\033[1;38;5;'"${C_SYNC_CODE}"'m'

    # Rate limit 색상 (저장된 값 사용)
    C_RATE=$'\033[38;5;'"${C_RATE_CODE}"'m'
    C_BURN=$'\033[38;5;'"${C_BURN_CODE}"'m'
    C_TIME=$'\033[38;5;'"${C_TIME_CODE}"'m'

    # 아이콘 색상
    C_I_BRANCH=$'\033[38;5;'"${C_BRANCH_CODE}"'m'
    C_I_TREE=$'\033[38;5;'"${C_TREE_CODE}"'m'
    C_I_DIR=$'\033[38;5;'"${C_DIR_CODE}"'m'
    C_I_MODEL=$'\033[38;5;'"${C_MODEL_CODE}"'m'
    C_I_STATUS=$'\033[38;5;'"${C_STATUS_CODE}"'m'
    C_I_SYNC=$'\033[38;5;'"${C_SYNC_CODE}"'m'
    C_I_CTX=$'\033[38;5;'"${C_CTX_CODE}"'m'
    C_I_RATE=$'\033[38;5;'"${C_RATE_CODE}"'m'
    C_I_BURN=$'\033[38;5;'"${C_BURN_CODE}"'m'
    C_I_TIME=$'\033[38;5;'"${C_TIME_CODE}"'m'
    C_I_THEME=$'\033[38;5;229m'

    # 배경색 (저장된 값 사용)
    C_BG_BRANCH=$'\033[48;5;'"${C_BG_BRANCH_CODE}"'m'
    C_BG_TREE=$'\033[48;5;'"${C_BG_TREE_CODE}"'m'
    C_BG_DIR=$'\033[48;5;'"${C_BG_DIR_CODE}"'m'
    C_BG_STATUS=$'\033[48;5;'"${C_BG_STATUS_CODE}"'m'
    C_BG_SYNC=$'\033[48;5;'"${C_BG_SYNC_CODE}"'m'
    C_BG_MODEL=$'\033[48;5;'"${C_BG_MODEL_CODE}"'m'
    C_BG_RATE=$'\033[48;5;58m'
    C_BG_TIME=$'\033[48;5;24m'
    C_BG_BURN=$'\033[48;5;94m'
    C_BG_CTX=$'\033[48;5;22m'
    C_BG_CTX_WARN=$'\033[48;5;94m'
    C_BG_CTX_CRIT=$'\033[48;5;52m'

    # 박스/칩 테두리 (고정)
    C_BOX=$'\033[38;5;240m'
    C_CHIP=$'\033[38;5;245m'

    # 칩/카드 배경색
    C_BG_LOC=$'\033[48;5;'"${C_BG_LOC_CODE}"'m'
    C_BG_GIT=$'\033[48;5;'"${C_BG_GIT_CODE}"'m'
    C_BG_SES=$'\033[48;5;'"${C_BG_SES_CODE}"'m'
    C_BG=$'\033[48;5;235m'

    # 배터리 배경색 (고정)
    C_BAT_EMPTY=$'\033[48;5;236m'
    C_BAT_GREEN=$'\033[48;5;23m'
    C_BAT_YELLOW=$'\033[48;5;94m'
    C_BAT_RED=$'\033[48;5;52m'

    # 컨텍스트 기반 동적 색상
    if [[ "$CONTEXT_PCT" -ge 70 ]]; then
        # 위험: 밝은 색상
        C_BRANCH=$'\033[1;38;5;'"${C_BRANCH_CODE}"'m'
        C_TREE=$'\033[1;38;5;'"${C_TREE_CODE}"'m'
        C_DIR=$'\033[1;38;5;'"${C_DIR_CODE}"'m'
        C_MODEL=$'\033[1;38;5;'"${C_MODEL_CODE}"'m'
        C_STATUS=$'\033[1;38;5;'"${C_STATUS_CODE}"'m'
        C_SYNC=$'\033[1;38;5;'"${C_SYNC_CODE}"'m'
        C_CTX=$'\033[1;91m'
        C_CTX_TEXT=$'\033[1;91m'
        CTX_ICON="${ICON_CTX_CRIT:-🔥}"
        C_BAT_FILL="$C_BAT_RED"
    elif [[ "$CONTEXT_PCT" -ge 50 ]]; then
        # 경고: 중간 밝기
        C_BRANCH=$'\033[1;38;5;'"${C_BRANCH_CODE}"'m'
        C_TREE=$'\033[1;38;5;'"${C_TREE_CODE}"'m'
        C_DIR=$'\033[1;38;5;'"${C_DIR_CODE}"'m'
        C_MODEL=$'\033[1;38;5;'"${C_MODEL_CODE}"'m'
        C_STATUS=$'\033[1;38;5;'"${C_STATUS_CODE}"'m'
        C_SYNC=$'\033[1;38;5;'"${C_SYNC_CODE}"'m'
        C_CTX=$'\033[1;38;5;208m'
        C_CTX_TEXT=$'\033[1;38;5;208m'
        CTX_ICON="${ICON_CTX_WARN:-🪫}"
        C_BAT_FILL="$C_BAT_YELLOW"
    else
        # 정상: 기본 색상
        C_BRANCH=$'\033[38;5;'"${C_BRANCH_CODE}"'m'
        C_TREE=$'\033[38;5;'"${C_TREE_CODE}"'m'
        C_DIR=$'\033[38;5;'"${C_DIR_CODE}"'m'
        C_MODEL=$'\033[38;5;'"${C_MODEL_CODE}"'m'
        C_STATUS=$'\033[38;5;'"${C_STATUS_CODE}"'m'
        C_SYNC=$'\033[38;5;'"${C_SYNC_CODE}"'m'
        C_CTX=$'\033[38;5;'"${C_CTX_CODE}"'m'
        C_CTX_TEXT=$'\033[0m'
        CTX_ICON="${ICON_CTX_NORM:-🔋}"
        C_BAT_FILL="$C_BAT_GREEN"
    fi
}

# Rate limit 동적 색상
get_rate_color() {
    if [[ "$RATE_LIMIT_PCT" -ge 80 ]]; then
        echo $'\033[1;91m'
    elif [[ "$RATE_LIMIT_PCT" -ge 50 ]]; then
        echo $'\033[1;38;5;208m'
    else
        echo $'\033[38;5;'"${C_RATE_CODE}"'m'
    fi
}
INIT_FUNC

    # 변경 플래그 해제
    MODIFIED=false

    # 성공 메시지
    show_save_message
}

# ============================================================
# 저장 완료 메시지
# ============================================================

show_save_message() {
    local y=$(($(tput lines) - 4))
    tput cup $y 2

    echo -e "\033[1;32m✓ Saved to $CUSTOM_COLOR_FILE\033[0m"
    echo -e "  \033[2mApply with: export CLAUDE_THEME=custom-2line\033[0m"

    sleep 1.5
}
